/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ChildInterface extends Interface {
    getFunction(nameOrSignature: "childName" | "getChildInfo" | "getParentInfo" | "parentBalance" | "parentName" | "sayHello"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'childName', values?: undefined): string;
encodeFunctionData(functionFragment: 'getChildInfo', values?: undefined): string;
encodeFunctionData(functionFragment: 'getParentInfo', values?: undefined): string;
encodeFunctionData(functionFragment: 'parentBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'parentName', values?: undefined): string;
encodeFunctionData(functionFragment: 'sayHello', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'childName', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getChildInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getParentInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'parentBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'parentName', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sayHello', data: BytesLike): Result;
  }

  

  export interface Child extends BaseContract {
    
    connect(runner?: ContractRunner | null): Child;
    waitForDeployment(): Promise<this>;

    interface: ChildInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    childName: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getChildInfo: TypedContractMethod<
      [],
      [[string, string, bigint]],
      'view'
    >
    

    
    getParentInfo: TypedContractMethod<
      [],
      [[string, bigint]],
      'view'
    >
    

    
    parentBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    parentName: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    sayHello: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'childName'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getChildInfo'): TypedContractMethod<
      [],
      [[string, string, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getParentInfo'): TypedContractMethod<
      [],
      [[string, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'parentBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'parentName'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'sayHello'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }