/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as childSol from './Child.sol/index.js';
export type { childSol };
import type * as parentSol from './Parent.sol/index.js';
export type { parentSol };
export * as factories from './factories/index.js';
export type { Child } from './Child.sol/Child.js';
export { Child__factory } from './factories/Child.sol/Child__factory.js';
export type { Parent } from './Parent.sol/Parent.js';
export { Parent__factory } from './factories/Parent.sol/Parent__factory.js';